apiVersion: skaffold/v2alpha3
kind: Config
# list all the config files we want to load into our clusters
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    #don't push image to dockerhub when building the image which is the default
    push: false
  # these are the things going to be built
  artifacts:
    - image: apahadi73/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      # tells skaffold how to handle the changes in sub-directory's file
      sync:
        manual:
          # sync all the files ending with ts extension
          - src: "src/**/*.ts"
            dest: .

    - image: apahadi73/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: apahadi73/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: apahadi73/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: apahadi73/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: apahadi73/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
